name: Backup Exercism solution

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: read

jobs:
  backup:
    if: startsWith(github.event.pull_request.head.ref, 'exercism-sync/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Configure Git identity
        run: |
          git config user.name "KowalczykPatryk"
          git config user.email "patrykkowalczyk565@gmail.com"

      - name: Fetch PR
        run: |
          git fetch origin ${{ github.event.pull_request.head.sha }}

      - name: Merge PR changes
        run: |
          git merge --no-commit --no-ff ${{ github.event.pull_request.head.sha }}

      - name: Create commit
        run: |
          git commit -m "${{ github.event.pull_request.title }}"

      - name: Push to main
        run: |
          git push origin main
